version: '3'

services:
    db:
        image: mongo:3.6
        restart: unless-stopped
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_DATABASE=db
        command: "mongod --port 27017 --bind_ip_all --dbpath /data/db"

    back:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - .:/usr/src/app
        ports:
            - 3000:3000
        environment:
            - MONGO_URL=mongodb://db:123456@db:27017/db
            - PORT=3000
        env_file:
            - .env
        depends_on:
            - db